#!/usr/bin/env python
# coding: utf-8

# In[2]:


import sys
from selenium import webdriver as wd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
#import pyperclip
import time
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import numpy as np
import urllib
import re
import datetime


options = wd.ChromeOptions()
options.add_argument('headless')
options.add_argument('window-size=1920x1080')
options.add_argument("disable-gpu")

url=input('url을 입력해주세요')


driver=wd.Chrome(executable_path='./chromedriver.exe',chrome_options=options)


driver.get(url)

total=driver.find_element_by_css_selector('#section_review > div.filter_sort_group__Y8HA1 > div.filter_evaluation_tap__-45pp > ul > li.filter_on__X0_Fb > a > em').text

total_num=int(total.replace(',','').replace(')','').replace('(',''))


print('전체리뷰수:',total_num)
x=int(input('몇개의 리뷰를 가져오시겠습니까'))

epochs=x//20

ss=x%20

result=[]
num=1
for epoch in range(epochs+1):
    if epoch!=epochs:
        
        for review in range(1,21):

            star=int(driver.find_element_by_css_selector('#section_review > ul > li:nth-child('+str(review)+') > div.reviewItems_etc_area__2P8i3 > span.reviewItems_average__16Ya-').text.replace('평점',''))
            text=driver.find_element_by_css_selector('#section_review > ul > li:nth-child('+str(review)+') > div.reviewItems_review__1eF8A > div.reviewItems_review_text__2Bwpa > p').text
            result.append([star,text])
    else:
        for review in range(1,ss+1):
            star=int(driver.find_element_by_css_selector('#section_review > ul > li:nth-child('+str(review)+') > div.reviewItems_etc_area__2P8i3 > span.reviewItems_average__16Ya-').text.replace('평점',''))
            text=driver.find_element_by_css_selector('#section_review > ul > li:nth-child('+str(review)+') > div.reviewItems_review__1eF8A > div.reviewItems_review_text__2Bwpa > p').text
            result.append([star,text])
        break
    if epoch <10:
        if num!=10:
            driver.find_element_by_css_selector('#section_review > div.pagination_pagination__2M9a4 > a:nth-child('+str(num+1)+')').click()
            time.sleep(1)
            num+=1
        else:
            driver.find_element_by_css_selector('#section_review > div.pagination_pagination__2M9a4 > a.pagination_next__3ycRH').click()
            time.sleep(1)
            num=1
    else:
        if num!=10:
            driver.find_element_by_css_selector('#section_review > div.pagination_pagination__2M9a4 > a:nth-child('+str(num+3)+')').click()
            num+=1
            time.sleep(1)
        else:
            driver.find_element_by_css_selector('#section_review > div.pagination_pagination__2M9a4 > a.pagination_next__3ycRH').click()
            num=1
            time.sleep(1)
    
driver.close()
df=pd.DataFrame(result,columns=['별점','리뷰'])
a=input('엑셀 이름을 입력해주세요')
now=datetime.datetime.now()

time_=('%02d%02d%02d-%02d%02d%02d' %(int(str(now.year)[2:]),now.month,now.day,now.hour,now.minute,now.second))

print('완료됐습니다')

df.to_excel(time_+'_'+a+'.xlsx',index=None)

